DROP DATABASE IF EXISTS todo_list;
DROP USER IF EXISTS `root`@`%`;
CREATE DATABASE IF NOT EXISTS todo_list CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `root`@`%` IDENTIFIED WITH mysql_native_password BY 'Bruski2505';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `todo_list`.* TO `root`@`%`;